### ISSUE TITLE
Set a "default" license in the settings?

### ISSUE THREAD

**Issue by ildyria** [LycheeOrg/Lychee-v3#124]
@bennettscience can you set a "default" license in the settings?

_Originally posted by @cryptomilk in https://github.com/LycheeOrg/Lychee/issues/71#issuecomment-441958867_

**Comment by bennettscience** [comment]
Yeah, I'll kick up a branch and start working on that this week. I'm back to work now after the holiday last week, so it'll take a little more time.

**Comment by bennettscience** [comment]
Ok, I have default licenses nearly ready to go and I'm wondering if an option should be 'All Rights Reserved' rather than 'none.' I don't know how descriptive 'None' is, and a non-licensed photo technically falls under All Rights Reserved when it comes to copyright (at least in the US, that's what I've found). Thoughts?

**Comment by ildyria** [comment]
I would say 'None' is the default (or empty string) as it is the default at the insertion in the DB.

**Comment by bennettscience** [comment]
Fair enough. I'll still throw All Rights Reserved into the options so users can set it specifically.

**Comment by SerenaButler** [comment]
It would be nice to be able to set a license for an album to avoid setting it for every individual image.
