### ISSUE TITLE
Static Code Analysis - Security

### ISSUE THREAD

**Issue by Himself132** [LycheeOrg/Lychee-v3#131]
### Detailed description of the problem
Wondering with the world of security vulnerabilities and hackers that we live in if anyone has run any static code analysis tools on the Lychee implementations?  If so is it done regularly as is industry standard?

### Steps to reproduce the issue
NA

### Output of the diagnostics (Settings => Diagnostics)
NA

### Browser and system
NA

**Comment by ildyria** [comment]
At the time of this writing there is not many company that actually do formal methods to prove their software, and I really mean prove the correctness and soundness of their software. I am currently doing a PhD in the field and applying formal methods is very very slow. Personally I will not do it on Lychee and I am usually working at a way more lower level: C or assembly.

However doing simple linting is naturally done with the IDE. I am using Phpstorm to code. It mostly check statically impossible path and forces me to write better Javascript (using `===` instead of `==`).

We also try to protect against most of the attack and I think we are doing pretty well at it. We implemented CSP policy etc...

The next big version of Lychee will be implemented over Laravel, you can actually find it here:
https://github.com/LycheeOrg/Lychee-Laravel
It provides the architecture with a better framework for code practice but also more safety nets, cf here:
https://www.cloudways.com/blog/best-laravel-security-practices/

Also see: https://github.com/LycheeOrg/Lychee/issues/68
