### ISSUE TITLE
[Q] How to generate missing sizes

### ISSUE THREAD

**Issue by cryptomilk** [LycheeOrg/Lychee-v3#134]
### Detailed description of the problem

I've updated to a newer Lychee release and noticed that there is a new `small` folder in the uploads folder. How can you manually generate missing image sizes?

I think this is something for the FAQ and provide a command so shell script how to do it.

**Comment by ildyria** [comment]
@cryptomilk Thank you for reminding me to actually prepare some file to generate them. :)
It is already implemented in the Laravel version, I just have not ported it to this version yet.

**Comment by ildyria** [comment]
Fixed with the latest push.

Go to your lychee installation, connect as admin and then go to:
https://example.com/php/index.php?function=Photo::genSmall&nb=5&from=0&timeout=1000
or
https://example.com/php/index.php?function=Photo::genSmall

- The number after `nb` defines how many images you want to process per run.  
  **default value: 5**
- The number after `from` defines from how many images do you want to process the run (useful to skip pictures you cannot generate small for).  
  **default value: 0**
- The number after `timeout` defines the timeout of the execution of the run.  
  **default value: 1000**

If `nb`, `from` and `timeout` are not provided the script will use the default value above.

**Comment by cryptomilk** [comment]
@ildyria Thanks you very much, that worked just fine. Could you add that information to https://github.com/LycheeOrg/Lychee/wiki/FAQ too please?

**Comment by d7415** [comment]
I considered that, but it's only a one-time problem on upgrade, so I'm not sure it's worth it... I'll see if I can point to it from the release notes somewhere.

**Comment by d7415** [comment]
Added to [3.2.7 Release Notes](https://github.com/LycheeOrg/Lychee/releases/tag/v3.2.7)
