### ISSUE TITLE
Photo Description overlay

### ISSUE THREAD

**Issue by dbw3** [LycheeOrg/Lychee-v3#167]
Enhancement request:  Please allow the photo _Description_ to be displayed in a fashion similar to the existing EXIF data overlay.  Ideally, it would also have its own "Display photo description overlay by default" setting.

The idea is to be able to show descriptive captions for photos without the user having to open the Info pane.

**Comment by ildyria** [comment]
This could be fairly easily implemented.

Before actually starting doing that, there are multiple small questions that need to be answered: 
- Where would that be placed ? On top of the picture like the Exif info ?
  + Bottom left (and hide Exif info)  ?
  + Bottom center (and hide Exif info) ?
  + Top right ?
- We might want to hide this when we display the info panel (or press `i`) ?
- Do we want to have this *rotate* with the Exif panel ? i.e. 1st click is Exif, second click is description (if available) ?

**Comment by dbw3** [comment]
Thanks for considering this request, @ildyria .  

- I would opt for bottom center placement, and have it float on top of the image if there isn't space for it otherwise (like EXIF info).  I think the description should be allowed the full width of the page.
- Hiding the caption when the info panel is displayed makes sense.
- I like the idea of having description rotate with the EXIF info, but it would be great if you could select whether or not to show EXIF info, Description, both (rotating), or neither in the settings.

**Comment by ildyria** [comment]
Why close the issue ? :')

**Comment by dbw3** [comment]
Sorry, I didn't mean to close the issue.

Actually, if EXIF info and Description are to rotate, it might sense to have them both at the bottom left.

Would it be difficult to offer a choice between an overlay starting at the bottom left (as EXIF info works now), or forcing the text below the image (centered) and rescaling the image to accommodate it?  I don't want to make this feature more complicated than it needs to be, but it would be nice to have the option.

**Comment by dbw3** [comment]
I'm really liking how Lychee works and looks.  The only thing I find lacking is the ability to show captions without bringing up the info panel.  I would be fine with whichever of the following seems most straight forward:

1. Description, EXIF Info, and neither are rotated by clicking the image, and which to show by default can be set on the settings page.

2. Description is shown below the picture and centered, and whether or not to show the Description is set on the settings page.  This shouldn't interfere with EXIF info, as that is shown on top of the picture and on the left side.

What makes the most sense to you?  Do you have any idea how soon this feature might be implemented?  Thanks.

**Comment by bennettscience** [comment]
I've been thinking about this for the last few days, about ways to implement this without cluttering up the interface too much. The idea of the fullscreen photo is to put as much of the picture on the screen with as little distraction as possible, hence the sidebar. In fact, researching other photo sites, very few offer a description (or even a title) on their fullscreen or slideshow views.

When you use the `i` hotkey, the info panel opens and persists, even when navigating photos. What if the photo was shifted to the left to preserve a good aspect ratio without adding more overlays to the photo view?

![small_photos](https://user-images.githubusercontent.com/3878010/51289866-ed335600-19cf-11e9-80f3-2e9be0b17867.gif)

Rotating the EXIF information in the bottom right is doable, but what is the length of time for the delay?  Does the user decide or is it pre-determined? If it's on the bottom of the image, you're also going to run into issues of readability because of light text on a light background. Or, what if the description is really long? Is the whole thing shown? Or is it truncated somehow?

(Here's a _really_ hacky implementation of the idea)

![2019-01-16_21-29-19](https://user-images.githubusercontent.com/3878010/51291718-148d2180-19d6-11e9-8a0e-558d8e40641c.gif)

I think I'm hesitant to put a lot of effort into something when it seems to be a fringe use case. Just my thoughts. It seems like a simple idea, but it's something that can get weedy really quickly without a really clear idea of what problem is being solved from a functional standpoint.

**Comment by dbw3** [comment]
The problem being solved is being able to tell a story with your photos using captions.  Or just explaining who is in a picture.  It didn't strike me as a fringe use case.

I do agree that shifting the image to the left of the info panel looks better and makes it more usable in general.  I would definitely like to see that change.  All of the details on the info panel may not be of interest to the target audience when sharing an album, which is why I wanted a less cluttered way of showing just the description, but it would be an improvement in any case.

Concerning rotating the Description and EXIF Info, I was imagining that the user would click on the picture to trigger it, just like EXIF Info is toggled on and off now.  I don't like the idea of it cycling automatically-- seems like that could be annoying.  Perhaps in the settings you could chose whether to show the EXIF info OR the Description, if that would simplify things.

I was hoping that showing the description overlay could be made optional on the settings screen so it wouldn't impact anyone who isn't interested in it.  If you turn it on, you'd be responsible for using appropriate descriptions that fit the screen.  But I do think that the whole description should be shown rather than truncating, even if it wraps to multiple lines.  Perhaps the size and color of the text, as well as wrapping and overflow behavior, could be changed in the "Personalize your CSS" section by defining a "caption" class.  I have already found "Personalize your CSS" to be useful; thanks to whoever set that up.

**Comment by bennettscience** [comment]
What about an added field in the setting that defines what shows: EXIF info or description?

**Comment by dbw3** [comment]
Yes, that sounds good.
