### ISSUE TITLE
Feature request: BackBlaze implementation

### ISSUE THREAD

**Issue by Vagning** [LycheeOrg/Lychee-v3#195]
Integration with BackBlaze for storing images in their cloud storage.

**Comment by d7415** [comment]
Unless I'm missing something, storing the images in BackBlaze isn't going to happen. Importing from there might be accepted as a PR.

If their layout is suitable to use as a CDN then I suppose that might be worth investigating as a generic feature, but a bespoke BackBlaze-based gallery sounds like a fork rather than a feature.

**Comment by Vagning** [comment]
BackBlaze offer a service (BackBlaze B2) just like Amazon S3, which is why I found it relevant.

**Comment by ildyria** [comment]
Related: https://github.com/LycheeOrg/Lychee/issues/44

IF someone makes a PR for it, then why not.
However I will not personally invest my time in it. Sorry.

**Comment by ildyria** [comment]
No news. Clothing.
