### ISSUE TITLE
Feature request: Support of GPSInfo/GpsTag (exif)

### ISSUE THREAD

**Issue by anthosz** [LycheeOrg/Lychee-v3#207]
Hello,

I think that can be a good idea to add these 2 features:
- Add the possibility to view a map when we select a picture (or assign a photo to a location in a map) via EXIF GPSInfo/GpsTag (https://www.sno.phy.queensu.ca/~phil/exiftool/TagNames/GPS.html)
- Add the possibility to sort album/picture via GpsTag (click on the map so that we can see all pictures that has been take in this location)

**Comment by d7415** [comment]
Ok, that's 3 parts.

#### 1) Show geotags on a map view
I like this. It should be able to be handled (almost?) completely in Lychee-front. We'd have to look at map providers/API keys though.

#### 2) Add geotags on a map view
This is more complicated, but potentially doable.

#### 3) Filter by location
This would be nice, but has a lot of design work. Particularly tolerances - it's no good saying "this exact location" because maybe you mean a square metre, or mile, or 10 miles. I picture a superimposed box on a zoomable map, but I have no idea how realistic that is.
This part would certainly need updates to the front and back ends.

**Comment by anthosz** [comment]
@d7415 Thank you for your feedback!

Concerning point 3, indeed, I would say like a selection by country/city (in a first time, depending of technical restictions), not at the specific address :)

**Comment by ildyria** [comment]
This is already Work in Progress in the V4.

cf here: https://github.com/LycheeOrg/Lychee-Laravel/issues/2
