### ISSUE TITLE
True Focal Length?

### ISSUE THREAD

**Issue by sat3ll** [LycheeOrg/Lychee-v3#244]
Currently (as of eff86e9) the Focal Length field is extracted via Exif tag **focallength**.
This works fine for Full Frame sensors (they're in 35mm after all) but does not convey the exact information for crop sensors. To account for them, when using _ExifTool_ at least, one can use the **focallengthin35mmformat** tag and it will take in account the crop factor.

Should the Focal Length field be changed from Exif tag **focallength** to **focallengthin35mmformat**? Or keep it and put the 35mm equivalent in parentheses? Or add a new field named "FF/35mm Focal Length Equivalent"?

**Comment by ildyria** [comment]
That's an interesting debate. The thing is if we take account of the 35mm equivalent focal length, then we will also need to take account of the equivalent aperture (which is a not well know fact)...
For :
- N the f-number
- f the focal length
- D the diameter of the entrance pupil

we have:  N = f / D

If you take the 35mm equivalent then you need to multiply the focal length by 1.6 or 1.5 or 2 depending of your camera, which means in order to preserve this equality you need to multiply the aperture N by the same value (D physically cannot change).

Making this change would probably confuse a lot of people and I suspect would also raise more bugs:
> *"I have a 70-200 mm lens f/4, why does it says the picture is taken a 320mm f/6.4 ?"*

**Comment by sat3ll** [comment]
> Making this change would probably confuse a lot of people and I suspect would also raise more bugs:
> 
> > _"I have a 70-200 mm lens f/4, why does it says the picture is taken a 320mm f/6.4 ?"_

Maybe changing Exif tag **focallength** to **focallengthin35mm** is a bit too much then. How about putting them in parentheses or adding a new tag?

> (...) will also need to take account of the equivalent aperture (which is a not well know fact)

Could be done in the same manner as mentioned above although as you said it, most people don't tend to pay attention to it.

**Comment by ildyria** [comment]
Will not be pursuied.
