### ISSUE TITLE
pre-pack zip-files for albums

### ISSUE THREAD

**Issue by jonas37** [LycheeOrg/Lychee-v3#253]
Hey, would it be possible to pre-pack the zip files for album-downloads?
As I understand at the moment, any zips are created for each user when trying to download a file. for large albums it takes some time until the zip is created. so it would be nice if there where an option to generate the zip after the creation of an album and store it on the server.

**Comment by ildyria** [comment]
Fixed in [v4](https://github.com/LycheeOrg/Lychee-laravel). We are using [ZipStream](https://github.com/maennchen/ZipStream-PHP) which avoid the creation of the zip file.

**Comment by jeyemwey** [comment]
@ildyria Hi, does this mitigate issues that we might have with max execution times? With large albums, the MXT will be much shorter than the download of an album, especially with bad reception.

We cannot set the MXT to hours just because of this script. I would prefer to cache (or "pre-pack" as the OP says) the zips so we don't need a php thread for each download. With a pre-packed zip, the items will just see apache just like the rest of the static files.

**Comment by ildyria** [comment]
I have no clue about the Max Execution Time and to be bluntly honest I don't really care about it.
