### ISSUE TITLE
Reference simlink when importing from local machine

### ISSUE THREAD

**Issue by ildyria** [LycheeOrg/Lychee-v3#29]
From : https://github.com/electerious/Lychee/issues/753

> I do not wish my images to be imported into Lychee, as this will dominate too much space duplicating the files. Can it be configured to use simlinks?

**Comment by vx3r** [comment]
Any update on this ?

**Comment by ildyria** [comment]
No sorry. :|

**Comment by ghost** [comment]
One option is to use reflink `(cp --reflink=always)` when copying the photos to the new structure. This requires a file system with COW support.

Another is to create hard links instead of copying. This would would work on most OS. Requires that the source files are on the same file system volume. Hard links are a little more risky as changes to the file would also change the source file.

The third option might be the best. Copy files without removing source files. It would be useful a re-scan of the source folder  for new images.

**Comment by d7415** [comment]
> The third option might be the best. Copy files without removing source files. It would be useful a re-scan of the source folder for new images.

This is already [available](https://github.com/LycheeOrg/Lychee/wiki/Settings#delete-imported-photos). [This](https://github.com/LycheeOrg/Lychee/wiki/Settings#skip-duplicates-on-upload) one will probably be useful too.

**Comment by ildyria** [comment]
Fixed in v4.
