### ISSUE TITLE
[question]Server error or Api not found

### ISSUE THREAD

**Issue by yomige** [LycheeOrg/Lychee-v3#49]
### Detailed description of the problem

![image](https://user-images.githubusercontent.com/4659346/46253192-a44ea480-c4a7-11e8-9e68-42f56c7a7b68.png)

### Steps to reproduce the issue

My php extentions:

```
[michael@cobcmw Lychee]$ php -m
[PHP Modules]
bcmath
Core
ctype
curl
date
dom
exif
filter
ftp
gd
hash
iconv
json
libxml
mbstring
mysqli
mysqlnd
openssl
pcre
PDO
pdo_mysql
pdo_sqlite
Phar
posix
Reflection
session
SimpleXML
sockets
SPL
sqlite3
standard
tokenizer
xml
xmlreader
xmlrpc
xmlwriter
zip
zlib

[Zend Modules]
```

Could you tell me , what's the problem?

### Browser and system

Both Chrome And Firefox，on Windows 10.

**Comment by crapmaster** [comment]
Have the same problem. Would have been great with a comment on how you resolved this.

**Comment by ildyria** [comment]
@crapmaster The reason that this answer is closed is because it is too generic and difficult to debug in such state.

Here are some stuff you can do:

1. Please press `F12`, select the tab `network` and refresh the page.

![2018-11-03_1920x1080_21 42 23](https://user-images.githubusercontent.com/627094/47957200-cf01b080-dfb1-11e8-8d90-a05123409b98.png)

2. Check that it is pointing to `php/index.php`. Then look for the code: 500 / 404 / 200 ... ?
3. Look at the response tab to check if there are any errors displayed.

**Comment by rabinnh** [comment]
In my case:
[Sun Dec 16 11:11:53.537154 2018] [:error] [pid 4816] [client xxxxxxx] PHP Parse error:  syntax error, unexpected '?' in /var/docs/Lychee/php/Modules/Session.php on line 80, referer: https://xxxxxxx/Lychee/

Appears to be an error in the PHP source.

Line 80 has a double question mark, as does line 91:

Log::notice(Database::get(), __METHOD__, __LINE__, 'User (' . $username . ') has logged in from ' . ($_SERVER['HTTP_X_REAL_IP'] ?? $_SERVER['REMOTE_ADDR']));

**Comment by d7415** [comment]
> Line 80 has a double question mark, as does line 91:

Oops. That's unrelated to the original issue and is my fault. I didn't check when the `??` operator was introduced. Apparently it was added in PHP7.

I'll go switch it to the (ugly) ternary version.

**Comment by d7415** [comment]
Also, I'm locking this as @cobcmw hasn't added anything and it seems to be attracting comments that should be separate issues.

**Comment by ildyria** [comment]
@rabinnh I would also advise you to update from PHP5 to PHP 7.2 (at least). See [here](http://php.net/supported-versions.php) why.
