### ISSUE TITLE
Permission problem on upload and data folder

### ISSUE THREAD

**Issue by meminens** [LycheeOrg/Lychee-v3#50]
### Detailed description of the problem

Documentation specifies that upload and data folders should be set to 750. However, Lychee shows an error message when permissions are set to 750. Error message says (paraprasing) "Unable to save configuration files. Please check upload and data folder permissions".

Only permission setting that works is 777. But this would potentially cause a security problem. I tried 755 and it didn't work either.

### Steps to reproduce the issue

1. Follow insturctions [here](https://github.com/electerious/Lychee/blob/master/docs/Installation.md) to install Lychee on an Apache server.
2. Open the installation directory in a browser.
3. Enter database credentials.
4. Error message pops up and album view won't show.

### Output of the diagnostics (Settings => Diagnostics)
`2018-09-29 23:24:10 - error - Lychee\Modules\Photo::add (50) 	- An upload-folder is missing or not readable and writable`

### Browser and system
Firefox on Mac
Ubuntu, Apache server

**Comment by ildyria** [comment]
Have you look at the instructions [here](https://github.com/LycheeOrg/Lychee/wiki/Installation) ?
The instruction you mentioned is on the old repo which explicitly states:
 "*Since the 1st of April 2018 this project has moved to it's own Organisation (https://github.com/LycheeOrg) where people are able to submit their fixes to it. We, the Organisation owners, want to thank electerious (Tobias Reich) for the opportunity to make this project live on.*".

If you are using Ubuntu, you should make sure that `www-data` (if I'm not mistaken) has the required rights to the said folder. You can also set the ownership with:
`sudo chown -R www-data:www-data uploads/ data/`

**Comment by meminens** [comment]
Thanks @ildyria. I did see the note about old repo but I could not find the new instructions which evidently states to use `775` as permissions. After modifying permissions to `775`, problem went away. Ownership was correctly set to `www-data` anyways. Issue was permissions.

Closing the issue.

**Comment by VictorLamoine** [comment]
I've just encountered this problem, I forgot to change the owner of the files.
I have modified the wiki so that other people don't forget to change the owner:
https://github.com/LycheeOrg/Lychee/wiki/Installation#2-download-lychee

**Comment by ildyria** [comment]
@VictorLamoine Thanks. :)
