### ISSUE TITLE
Going to my website i have to add index.html to the end for it to work

### ISSUE THREAD

**Issue by worldofmadness** [LycheeOrg/Lychee-v3#62]
### Detailed description of the problem
https://siteiown.com i have to add /index.html to the end for it to goto the site.

i host on a plesk system.

Chrome
Firefox
Edge
IE

**Comment by ildyria** [comment]
I don't understand your issue. There is a [index.html](https://github.com/LycheeOrg/Lychee/blob/master/index.html) at the root of this repository.

After further though, it is probably because of the order apache is fetching the files. Check the priority between index.htm, index.html in your apache config etc...

**Comment by worldofmadness** [comment]
goto http://historicwelshconstabularies.co.uk then goto http://historicwelshconstabularies.co.uk/index.html  for some reason it doesnt like it with out the index.html at the end

**Comment by ildyria** [comment]
Well in my case (Linux, Chrome) both show me the same website (Lychee).
A cache problem maybe ? (CTRL + F5)

**Comment by worldofmadness** [comment]
yeah i cleared the cach contrl f5 didnt force it was corrupted cache
