### ISSUE TITLE
[FEATURE] Add possibility to set a license

### ISSUE THREAD

**Issue by cryptomilk** [LycheeOrg/Lychee-v3#71]
### Detailed description of the problem

It should be possible that you can select a license e.g. [Creative Commons](https://creativecommons.org/) in the global settings for your images. And that you can change it for individual images, but by default select the global one.

**Comment by bennettscience** [comment]
I started working on this on my fork of Lychee. I'm having a couple problems, though, because my PHP/MySQL knowledge is pretty thin.

1. Updating the table

With a new install, it'll be fine because adding a `license` field to `php/database/photos_table.sql` creates the user's table with an empty license column. It's a bigger issue with the update process for existing users. I tried adding a call on the [Photo module](https://github.com/bennettscience/Lychee/commit/d47aa5006f34ca3e1b1adc198d7f2a87e6ff25d4) but I don't think that's the best way to achieve that.

2. Updating a photo's license

[I've added some UI](https://github.com/bennettscience/Lychee/commit/c29065c69871b544a30da9c499a9bb46af2d0001) updates that pulls the license info from the photo's JSON data. Looking at the other methods, I thought this would call the `basicModal`, but the event listener isn't being appended and I'm not sure why without digging in deeper.

I have not changed anything in the Settings module for setting a default or in setting album-level defaults. I'd appreciate insight/help on pulling this first pass together, though.

**Comment by cryptomilk** [comment]
Do you plan to provide a list of licenses to select?

It might make sense to add a link to https://tldrlegal.com/

Example:
https://tldrlegal.com/license/creative-commons-attribution-noncommercial-sharealike-4.0-international-(cc-by-nc-sa-4.0)

**Comment by bennettscience** [comment]
That's the ultimate end goal, similar to how flickr provides a drop down
list of licenses. So the SQL column length rule will need to change in the
branch (set to varchar(20) right now). I was playing with plaintext just to
get the concept working for now.

**Comment by ildyria** [comment]
> With a new install, it'll be fine because adding a license field to php/database/photos_table.sql creates the user's table with an empty license column. It's a bigger issue with the update process for existing users. I tried adding a call on the Photo module but I don't think that's the best way to achieve that.

This is not how you should do it as it will break forward compatibility. On a new install every updates are executed, so you can just create a new `update_03020X.php` file in that database folder with nearly the same content as  https://github.com/LycheeOrg/Lychee/blob/master/php/database/update_030204.php : change `update_030204` for `update_030205`, remove lines 23 to 27, and change `lens` for `license.

The varchar(100) can indeed be changed for varchar(20). :+1:

**Comment by bennettscience** [comment]
Ah, ok, that makes more sense. What am I missing for the `basicModal` event
listener?

**Comment by ildyria** [comment]
I also see that you are directly editing the `dist/main.js`. That is the wrong method.
Please have a look at https://github.com/LycheeOrg/Lychee/wiki/Build :)

The front end is generated by: https://github.com/LycheeOrg/Lychee-front
It provides a better structure. In your case you will need to modify:
https://github.com/LycheeOrg/Lychee-front/blob/master/scripts/photo.js (for the setLicense)
https://github.com/LycheeOrg/Lychee-front/blob/master/scripts/build.js (for the basic modal menu)
https://github.com/LycheeOrg/Lychee-front/blob/master/scripts/lychee_locale.js (for the locale)
https://github.com/LycheeOrg/Lychee-front/blob/master/scripts/sidebar.js (to display the chosen license)

**Comment by ildyria** [comment]
> Ah, ok, that makes more sense. What am I missing for the `basicModal` event listener?

Have a look at: https://github.com/LycheeOrg/Lychee-front/blob/master/scripts/sidebar.js#L24
You are missing a `#` in front of your `edit_license`. This is Jquery/CSS selection. The `#` indicate an to select on an `id`.

**Comment by bennettscience** [comment]
OK, that was my problem. I'll go back today and keep poking.

Thanks for the coaching 😀

**Comment by bennettscience** [comment]
Ok, I did some work this afternoon to break changes out into my fork of [Lychee-front]. The only other problem I'm having is getting the updated `Photo` module to recognize a new method. 

The new method is on [line 1156](https://github.com/bennettscience/Lychee/blob/feature/license/php/Modules/Photo.php#L1156), and here's my API call from [`photo.js`](https://github.com/bennettscience/Lychee-front/blob/feature/license/scripts/photo.js#L650) on the frontend. Lychee displays an error that the function can't be found.

**Comment by ildyria** [comment]
did you do `npm install` and `npm run compile` ?

**Comment by bennettscience** [comment]
Yes, frontend compiles correctly each time.

**Comment by ildyria** [comment]
you need to add a method in admin.php to forward the call to photo.php

**Comment by bennettscience** [comment]
Ahhh...didn't even think to look there. Thanks again.

**Comment by cryptomilk** [comment]
@bennettscience can you set a "default" license in the settings?
