### ISSUE TITLE
Suggestion: Specify new system requirements in commit messages

### ISSUE THREAD

**Issue by d7415** [LycheeOrg/Lychee-v3#83]
In e5a2925b29cd5b520d47175453a437dc6984c8e9 the commit message just says "* Added video thumbnail". This commit adds several system requirements, including php-ffmpeg and composer.

From what I can tell, php-ffmpeg is only required for generating video thumbnails, so could presumably be optional. I accept that this would complicate matters and so can understand making it a requirement for simplicity.

Less clear from issues and commits is the sudden requirement for composer. I had all of the specified requirements installed. Having seen #77 appear I had even installed php-ffmpeg. In spite of this, I had to install composer before Lychee would open, and this was not mentioned in the commits (or issues/PRs).

I suppose the new composer requirement sort of fixes this (though maybe the [update](https://github.com/LycheeOrg/Lychee/wiki/Update) page should include a `composer update`), but please could developers mention major changes like this in commit messages?

Thank-you.

**Comment by humantex** [comment]
I thought I would add a comment concerning the new requirements... Although I'm making an educated guess, I'd doubt that most of the major shared hosting providers either already have installed - or will agree to install - ffmpeg and/or some flavor of IMagick. The same can be said for access to any hosting account utilities that can run composer commands.

A quick check shows that GoDaddy, HostGator, Hostinger, do not allow ffmeg on shared hosting. It's seen as a resource intensive module, and only available in their big ticket plans.

From a user's perspective, adding these requirements will limit where Lychee can run, and at what cost. If someone already has a shared hosting account where these needs can't be met, that would mean changing hosts - or upgrading to a VPS or some other unmanaged solution with a significant increase in cost. i.e., $3 per month, to $20-30 per month.

My provider **does** include ffmpeg and ImageMagick as defaults in their cPanel accounts, but SSH access to run composer commands on the server is an additional cost. Honestly, it's not worth the added expense for me to get video thumbnails auto-generated during uploads. I'd be just as happy to extract a thumb locally and upload it as a single/attached frame as a placeholder - if that option was available instead of taxing ffmpeg to extract one for me.

As for running composer for dependency installs and not wanting to duplicate what may already be available...

If Lychee was heading towards being a SaaS project as a multi-tenant install, I can understand a need to not have 100's of duplicate libraries - but - it might be a better option to run a checking routine and if no libraries/files were found, use a PHP-based option to retrieve and install them. See: https://www.sitepoint.com/using-curl-for-remote-requests

**Comment by ildyria** [comment]
Indeed commit should when there is a big change in the system requirement.
The requirement of ffmpeg has been turned off. Lychee is now usable without it.
